######################## default configuration ####################
baseURL = "/"
title = "Jobwork Center"
#theme = "bizcraft-hugo"
# language
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "#" # get your shortname form here : https://disqus.com


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/fontawesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/animate.css"
[[params.plugins.css]]
link = "plugins/prettyPhoto.css"
[[params.plugins.css]]
link = "plugins/owl/owl.carousel.css"
[[params.plugins.css]]
link = "plugins/owl/owl.theme.css"
[[params.plugins.css]]
link = "plugins/flex-slider/flexslider.css"
[[params.plugins.css]]
link = "plugins/cd-hero/cd-hero.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/style-switcher.js"
[[params.plugins.js]]
link = "plugins/owl/owl.carousel.js"
[[params.plugins.js]]
link = "plugins/jquery.prettyPhoto.js"
[[params.plugins.js]]
link = "plugins/flex-slider/jquery.flexslider.js"
[[params.plugins.js]]
link = "plugins/cd-hero/cd-hero.js"
[[params.plugins.js]]
link = "plugins/isotope.js"
[[params.plugins.js]]
link = "plugins/ini.isotope.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/jquery.easing.1.3.js"
[[params.plugins.js]]
link = "plugins/jquery.counterup.min.js"
[[params.plugins.js]]
link = "plugins/waypoints.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

# main menu
[[menu.main]]
name = "Services"
URL = "service"
weight = 1

[[menu.main]]
name = "About"
URL = "about"
weight = 4

[[menu.main]]
name = "Testimonials"
URL = "#"
weight = 3

#[[menu.main]]
#name = "Portfolio"
#URL = "portfolio"
#weight = 2

[[menu.main]]
name = "News"
URL = "blog"
weight = 5

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 6


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "JAMFlow"
# contact info
address = "Sudama Complex, 2nd floor, Near Sudama Chowk, Porbandar"
phone = "+91 9428 626 850 | +91 9909 460 860"
email = "jobworkcenterpbr@gmail.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# footer content
footer_content = "For any inquiry feel free to call or mail. Your personal visit will definately make us happy."
# copyright
copyright = "Copyright &copy; 2021 Jobwork Center made in ❤️ with JAMFlow"

# flickr photos
[[params.flickr_photos]]
image = "images/gallery/1.jpg"
[[params.flickr_photos]]
image = "images/gallery/2.jpg"
[[params.flickr_photos]]
image = "images/gallery/3.jpg"
[[params.flickr_photos]]
image = "images/gallery/4.jpg"
[[params.flickr_photos]]
image = "images/gallery/5.jpg"
[[params.flickr_photos]]
image = "images/gallery/6.jpg"
[[params.flickr_photos]]
image = "images/gallery/7.jpg"
[[params.flickr_photos]]
image = "images/gallery/8.jpg"
[[params.flickr_photos]]
image = "images/gallery/9.jpg"

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
  